config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  delete '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  
  root to: 'welcome#home'
  delete '/delete/:id', to: 'exercises_workouts#destroy', as: 'delete'

  resources :users do 
    resources :comments, only: [:index]
    resources :workouts, only: [:index]    # my page link keeps redirecting to previouse user##
  end

  resources :workouts do
    resources :comments, only: [:new]
  end

  resources :comments

  resources :exercises

  get '*path', to: 'errors#error_404', via: :all
  

end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :exercises_workouts
  has_many :exercises, through: :exercises_workouts

  validates :name, presence: true, uniqueness: true
  validates :exercises_workouts, presence: {message: "Sets and reps can't be blank!"}

  accepts_nested_attributes_for :exercises_workouts, reject_if: proc { |attributes| attributes['sets'].blank? || attributes['reps'].blank? } 
 
  scope :alphabetically, ->{ order(:name) }

  def creator
    self.user.name
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @workouts = @user.workouts
      render 'user_workouts'
    elsif params[:alphabetically]
      @workouts = Workout.alphabetically
    else
      @workouts = Workout.all
    end
  end

  def new 
    @exercises = Exercise.all
    @workout = Workout.new
    10.times {@workout.exercises_workouts.build}
  end

  def create
    # Make it so that exercises workout are no blank
    # When re-rendered with error messages
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to workout_path(@workout)
    else
      @exercises = Exercise.all
      @errors = @workout.errors.full_messages
      10.times {@workout.exercises_workouts.build}
      render 'new'
    end
  end

  def show
    current_workout
    @user = User.find_by_id(@workout.user_id)
    redirect_to workouts_path, alert: "That workout does not exist" if @workout.nil?
  end 

  def edit
    redirect_if_not_authorized(current_workout)
    @exercises = Exercise.all
    5.times {@workout.exercises_workouts.build}
  end

  def update
    current_workout 
    if @workout.update(workout_params)
      redirect_to workout_path(@workout)
    else
      @errors = @workout.errors.full_messages  
      render 'edit'                               
    end
  end

  def destroy
    redirect_if_not_authorized(current_workout)
    @workout.destroy
    redirect_to user_workouts_path(current_user)
  end

  private
  def workout_params
    params.require(:workout).permit(:name, exercises_workouts_attributes: [:id, :exercise_id, :sets, :reps])
  end

  def current_workout
    @workout ||= Workout.find_by_id(params[:id])
  end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def delete_exercise(exercise)
    if params[:action] == 'edit' && exercise.object.id
      link_to "Delete", delete_path(exercise.object.id), method: :delete, class: "btn btn-danger btn-sm"  
    end
  end
end

app/views/workouts/_comments.html.erb
<ul>
  <% @workout.comments.each do |comment| %>
    <li><%= link_to comment.user.name, user_workouts_path(comment.user)%><%= " said: #{comment.content}" %></li>
    <% if comment.user == current_user %>
      <%= button_to "Edit", edit_comment_path(comment), method: :get %>
      <%= button_to "Delete", comment_path(comment), method: :delete %>
    <%end%>
    <br>
  <%end%>
</ul>
<h4><%= link_to "Create a new comment", new_workout_comment_path(@workout) %></h4>

app/views/workouts/_exercises.html.erb
<ul>
  <% @workout.exercises.each do |exercise| %>
    <%= link_to exercise.name, exercise_path(exercise), target: "_blank" %>
    <li>
      <%= image_tag exercise.image, size: "100x100" %>
      <%= exercise.sets_and_reps(@workout) %><br><br>
    </li>
  <%end%>
</ul>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
  <%= f.label "Create a name for your workout" %><br>
  <%= f.text_field :name, placeholder: "The Crippler" %><br><br>
  
  <p>Add Exercises</p>
    <%= f.fields_for :exercises_workouts do |e| %>
      <%=delete_exercise(e)%>
      <%= e.collection_select :exercise_id, @exercises, :id, :name, value: :exercise_id %>
      <%= e.label :sets %>
      <%= e.number_field :sets, min: 1, max: 100 %>
      <%= e.label :reps %>
      <%= e.number_field :reps, min: 1, max: 100  %><br>
      <br><br>
    <% end %>
    <%= f.submit class: 'btn btn-primary btn-lg mb-5' %>
  <% end %>  

app/views/workouts/edit.html.erb
<h1>Edit a workout</h1>

<%= render 'form' %>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<%=form_tag(workouts_path, method: 'get') do %>
  <%= hidden_field_tag :alphabetically %>
  <%= submit_tag "Order from A-Z" %>
<%end%>

<ul>
<% @workouts.each do |workout| %>
  <li><%= link_to workout.name, workout_path(workout) %> by <%= link_to workout.creator, user_workouts_path(workout.user) %>  </li>
<% end %> 
</ul>

app/views/workouts/new.html.erb
<h1>Make a new workout</h1>

<%= render 'form' %>

app/views/workouts/show.html.erb
<h1><%= @workout.name %></h1>

<% if @workout.user == current_user %>
  <%= button_to "Edit", edit_workout_path(@workout), method: :get, class: "btn btn-secondary" %>
  <%= button_to "Delete", workout_path(@workout), method: :delete, class: "btn btn-danger" %>
<%end%>

<h2>Created by: <%= link_to @workout.creator, user_workouts_path(@user) %></h2>

<h2>Exercises</h2>

<%= render 'exercises' %>

<h3>Comments</h3>

<%= render 'comments' %>

app/views/workouts/user_workouts.html.erb
<h1><%= @user.name %></h1>

<h3>Workouts</h3> 

<ul>
  <% @user.workouts.each do |workout| %>
    <li><%= link_to workout.name, workout_path(workout) %></li>
  <% end %>
</ul>