config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  delete '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  
  root to: 'welcome#home'
  delete '/delete/:id', to: 'exercises_workouts#destroy', as: 'delete'

  resources :users do 
    resources :comments, only: [:index]
    resources :workouts, only: [:index]    # my page link keeps redirecting to previouse user##
  end

  resources :workouts do
    resources :comments, only: [:new]
  end

  resources :comments

  resources :exercises

  get '*path', to: 'errors#error_404', via: :all
  

end

app/models/user.rb
class User < ApplicationRecord
  has_many :workouts
  has_many :comments

  has_secure_password
  validates :name, :email, presence: true, uniqueness: true

  def self.from_oauth(auth)
    User.find_or_create_by(provider: auth['provider'], uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.password = SecureRandom.hex(15)
      u.email = auth['info']['email']
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_if_not_logged_in    ##Make Crud Actions for current_user owned objects##

  def edit
    current_user
  end

  def update

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_workouts_path(@user)
    else
      @errors = @user.errors.full_messages
      render 'new'
    end  
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :height, :weight)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label "Username", class: "form-label fw-bold" %><br>
  <%= f.text_field :name, class: "form-control-lg" %><br><br>

  <%= f.label :email, class: "form-label fw-bold" %><br>
  <%= f.email_field :email, class: "form-control-lg" %><br><br>

  <%= f.label "Weight(in pounds)", class: "form-label fw-bold" %><br>
  <%= f.number_field :weight, min: 0, class: "form-control-lg" %><br><br>

  <%= f.label "Height(in inches)", class: "form-label fw-bold" %><br>
  <%= f.number_field :height, min: 0, class: "form-control-lg" %><br><br>

  <%= f.label :password, class: "form-label fw-bold" %><br>
  <%= f.password_field :password, class: "form-control-lg" %><br><br>

  <%= f.label :password_confirmation, class: "form-label fw-bold" %><br>
  <%= f.password_field :password_confirmation, class: "form-control-lg" %><br><br>

  <%= f.submit class: "btn btn-primary" %>
<% end %>  

app/views/users/new.html.erb
<h1>Become A Gritty Member</h1>
<%= render partial: 'form' %>


<%= button_to "Log in with Google", '/auth/google_oauth2', class: "position-absolute top-50 start-50 translate-middle btn btn-primary btn-lg" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>Workouts</h3> 

<ul>
  <% @user.workouts.each do |workout| %>
    <li><%= link_to workout.name, workout_path(workout) %></li>
  <% end %>
</ul>