config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  delete '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  
  root to: 'welcome#home'
  delete '/delete/:id', to: 'exercises_workouts#destroy', as: 'delete'

  resources :users do 
    resources :comments, only: [:index]
    resources :workouts, only: [:index]    # my page link keeps redirecting to previouse user##
  end

  resources :workouts do
    resources :comments, only: [:new]
  end

  resources :comments

  resources :exercises

  get '*path', to: 'errors#error_404', via: :all
  

end

app/views/layouts/_errors.html.erb
<% flash.each do |type, msg| %>
  <div>
  <p class="alert alert-danger w-50 " role="alert"><%= msg %></p>
  </div>
<% end %>

<div >
  <% if @errors %>
    <ul>
    <% @errors.each do |error| %>
      <li class="alert alert-danger w-50" role="alert"><%= error %></li>
    <% end %> 
    </ul>
  <%end%>
</div>

app/views/layouts/_links.html.erb
<% if logged_in? %>
  <%= link_to 'Logout', logout_path, method: :delete %>
  <%= link_to "My workouts", user_workouts_path(current_user) %>
  <%= link_to 'Exercises', exercises_path %>
  <%= link_to 'Create a new workout', new_workout_path %>
  <%= link_to 'Workouts', workouts_path %>
<%else %>
  <%= link_to 'Login', new_session_path %>
  <%= link_to "Create an account", new_user_path %>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- <% if logged_in? %>
  <ul class="nav border border-3 mb-4 rounded-pill">
    <li class="nav-item text-reset">
      <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link active"%>
    </li>
    <li class="nav-item text-reset">
      <%= link_to "My workouts", user_workouts_path(current_user), class: "nav-link active" %>
    </li>
    <li class="nav-item text-reset">
      <%= link_to 'Exercises', exercises_path, class: "nav-link active" %>
    </li>
    <li class="nav-item text-reset">
      <%= link_to 'Create a new workout', new_workout_path, class: "nav-link active" %>
     
    </li>
    <li class="nav-item text-reset">
      <%= link_to 'All Workouts', workouts_path, class: "nav-link active" %>
     
    </li>
  </ul>
<% else %>
  <ul class="nav border border-3 mb-4 rounded-pill">
    <li class="nav-item">
      <%= link_to 'Login', new_session_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to "Create an account", new_user_path, class: "nav-link" %>
    </li>
  </ul>
<%end%> -->

<!-- <nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="../assets/logo.png" alt="Gritty Logo" width="150" height="150">
    </a>
  </div>
</nav> -->

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="../assets/logo.png" class="d-inline-block align-text-top" alt="Gritty Logo" width="50" height="50">
    </a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- CREATE THE NAVEBAR WITH MATCHING COLORS -->
<!-- ADD LOGO TO FAVICON  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gritty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" href="../assets/logo.png" style="font-size: 1000%;"/>
<!-- 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> -->

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/errors' %>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>